### ISSUE TITLE
Lib visibility

### ISSUE THREAD

**Issue by azrafe7** [hxDaedalus/hxDaedalus#27]
I think it should be a wise move to link the related Skial's blog issue in the README and/or add a png/gif to roughly illustrate the purpose of the lib. What you think?

**Comment by Justinfront** [comment]
Yep sounds good idea, would be nice to get Cedric interested he may have ideas on documentation.  I looked at embedding video in github wikki but can't remember if it was possible or practical.

**Comment by Justinfront** [comment]
Really would be nice to create a Java example repository, which has pure Java example using a haxe created Jar and adding some explaination but not yet sure how to do this, and similar with js, I expect it would be useful to try to mesh the js stuff with something webgl like threejs so normal javascript users could use a haxe generated js with thier code. All these things are somewhat overkill accept they start to break the ground for similar projects allowing haxe to become the language to code such projects in to serve copy and paste users in other languages.
