### ISSUE TITLE
multilayer

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#30]
started on multilayer example/experiment, at moment example is quite limited and it's only one way, but concept seems to work fine and seems quite simple to use.  Currently only on the openfl experiments repository.

**Comment by Justinfront** [comment]
have updated the code but still working on it.

**Comment by azrafe7** [comment]
Nice!

**Comment by Justinfront** [comment]
Sorry it's taking me awhile to get this working properly.

**Comment by Justinfront** [comment]
Ok think I have solved the issue will upload soon..

**Comment by azrafe7** [comment]
I took a look at the code and it's getting quite complex (though I might be wrong as haven't actually tried to solve the problem myself, and might be oversighting something).

Anyway I wanted you to know that I found a way to ~easily work around png embedding in openfl/html5 and avoid cross origin issues. The solution was hidden inside the macro code and haven't found any doc about it, but... Openfl offers an optional `onload` callback when embedding a bitmap via metatag, and actually also encodes it in base64.

Here's how it would look using the FromBitmap demo as example:
```haxe
@:bitmap("assets/FromBitmap.png")
class TestImage extends flash.display.BitmapData {}

class Main extends Sprite
{
	...

    _bmp = new Bitmap();
	addChild(_bmp);
	
	#if html5
		new TestImage(0, 0, function(bmd) {
			_bmp.bitmapData = bmd;
			onImageLoaded();
		});
    #else		
        _bmp.bitmapData = new TestImage(0, 0);
		onImageLoaded();
	#end

	...

	function onImageLoaded() {
        
        // create an object from bitmap
        _object = BitmapObject.buildFromBmpData(_bmp.bitmapData);

		...
```

This could also be simplified further by using an approach similar to what you have in your `ImageLoader`.

PS: also no more need to add the asset in the application.xml

**Comment by Justinfront** [comment]
It would be good if you can add that so I have a link that works, certainly it might help get some thoughts from Flash Cedric.

The example are stable now, the concepts were simple but detail and stability eluded me for quite some time, but now with a solution I am sure it can be improved. 

Ideally hxDaedalus should have easy to use portals - it needs consideration so that examples would be simple.

**Comment by Justinfront** [comment]
Ok I have been thinking about this and between meshes maybe an Astar approach is required, especially  if you consider systems with a hundred meshes.  So you would start by precalculating the path lengths between portals on a single mesh and then you would have the shortest between any 2 portals on a mesh.  So if you have a mesh between two meshes then you would already have the pre-calculated shortest paths between portals for the piggy in the middle graph. To develop this further we probably need quite a few meshes.

**Comment by azrafe7** [comment]
About the ImageLoader to work around the CORS issues for openfl/nme js target: I made a _seemingly_ working thing [here](https://gist.github.com/azrafe7/10175feabfa6891322fc), based on your ImageLoader class. Not sure it's _complete/fully functional_, so haven't made a PR yet.

Talking about portals and pathfinding across separate maps/floors...

**Comment by azrafe7** [comment]
I have something in mind, but haven't had the time to try and code it down yet. I'll probably fiddle with it tomorrow. Basically my stream of thoughts goes like:

 - make an array of floors (mapping to a Mesh)
 - make the floors as mesh on top of each other (but draw them with an offset, to ease the calcs)
 - retain a list of portals (BUT bidirectional)
 - f.e. the first floor doesn't need to know about the 3rd, info will be delegated to what the 2nd one knows about its portals
 - when trying to find the shortest path between two floors locations, choose the shorter one by comparing the paths' length to the _nearest_ portals
 - assign the entity's position based on its current floor/map (and remember its last position)

Re-reading the bullet points now... I hope something got through, as I guess I've not explained myself very well! ;D Late here! hehe

**Comment by Justinfront** [comment]
Does this work with sky walkways? This seems to limit to physical buildings and would not work with more abstract game structures. For instance travelling between planets, walking on planet where physical spaces are distorted between portals in different ways especially if there are some black holes.

However consider polygonal's A* wayfinding also in Haxe.
http://lab.polygonal.de/wp-content/assets/110722/flash.html

I can dig out an away3d version somewhere of a car driving round london centre, from memory the drawing code was rather tied to logic and flash, but I expect that is just for the demo, so I have some concept of it's workings, so I could try a blend, or maybe the equivalent A* wayfinding is already in hxDaedalus, but I think that it's important to consider mesh approach as only superior for some uses, a blend can have advantage of both.

If we consider portals as nodes on an A* network then we can set weighting between nodes (portals) within a mesh as the findPath length between portals on the mesh, I am just unsure if these meshes typically allow bridges/crossovers.  But you can traverse the A* linked structure normally but only render to screen via the meshes when moving between portals accross a mesh.  Obviously most end and start points will be on a mesh but they can be treated as dynamic portals on the A* structure.

**Comment by Justinfront** [comment]
If you look at Doune Castle it would require 6 nodes of polygonal's wayfinding.

**Comment by azrafe7** [comment]
Ooohh... Now I'm starting to get what you mean...
This requires some thinking. Not sure there's a solution simple enough though.

**Comment by azrafe7** [comment]
There's this on SO http://stackoverflow.com/questions/14428331/a-admissible-heuristics-on-a-grid-with-teleporters, don't know if it could be of help. But in general I think that this goes beyond the common usage of the lib (though it would be a great thing to showcase).

I'd only add that it would be really interesting to know how Cedric/Baczynski/Patel would approach the problem.

**Comment by Justinfront** [comment]
azrafe7

Ok here's some notes on what I will probably try at weekend.  Start reading here:
http://lab.polygonal.de/?p=185

To get started I need some polygonal stuff...

haxelib install polygonal-core
haxelib install polygonal-ai
haxelib polygonal-native
haxelib polygonal-gl
haxelib polygonal-ui
haxelib polygonal-printf

Then I modifiy the example in polygonal-ai 
( usr/lib/haxeLibrary/polygonal/polygonal-ai/1,0,0/examples/astar ) note to self maybe consider git versions as 1,0,0 is prob old?

So first the compile file
https://github.com/polygonal/ai/blob/master/examples/astar/compile.hxml#L5

add these lines to make life easy.

-lib polygonal-ai
-cmd open astar.swf

then in the TestPathFinder I want to check I can have cross paths without issues...

https://github.com/polygonal/ai/blob/master/examples/astar/TestPathFinder.hx#L95
Add a birdirectional link between 0 and 6 proving that cross overs are not a problem.

0,6];

comment out these lines just below to use hardcoded data instead.
		//nodeData = _editor.getNodeData();
		//arcData = _editor.getArcData();

run as normal, you have to draw a triangle then press 'space', it will delete it and use hardcode data.

Next question how might we adjust the weighting between nodes, so that we can set the weighting of portals accross a mesh.  

In hxDaedalus we measure the path length between portals on a mesh
                        sampler.reset();
			entity.x = portal0.x - pos.x;
		        entity.y = portal0.y - pos.y;
			pathfinder.findPath( portal1.x - pos.x, portal1.y - pos.y, path );
                        var arcCost = path.length;

Then in our modified polygonal TestPathFinder we can insert the relevant arcCost

https://github.com/polygonal/ai/blob/master/examples/astar/TestPathFinder.hx#L138
_graph.addMutualArc(source, target, arcCost);

But one issue seems to be that we would want to make distance of the waypoint to always be 1, since we don't want the portals to be based on real distances, even if we render them to a view in real space.
https://github.com/polygonal/ai/blob/master/src/de/polygonal/ai/pathfinding/AStarWaypoint.hx#L86

Between our hxDaedalus meshes the https://github.com/polygonal/ds/blob/master/src/de/polygonal/ds/GraphArc.hx
would need to have probably a high cost ( walking upstairs should be expensive ).
_graph.addMutualArc(source, target, 1000);

I am pretty sure putting this together will take some work but I think the concept is very sound.  Obviously aspects such as drawing a route will mean going in and out of meshes as we traverse the graph.

**Comment by Justinfront** [comment]
I have pushed a revised version to a new branch based on the above, still needs some work but seems to work.

**Comment by Justinfront** [comment]
Well it's beginning to get there now you can click round.

**Comment by azrafe7** [comment]
Just tested it and WOW... verrry nice! That's progress!! Keep it up!!!

**Comment by Justinfront** [comment]
Just uploaded small change that works better

**Comment by Justinfront** [comment]
I don't suppose you fancy making the html work, I can't work on it tomorrow anyway and may not get back to it till weekend anyway. 

I should really make the graphics look better and I am sure the code needs more thought but would be nice to share progress online, even though it's even more complex quite pleased with the concept it might actually be feasible to use with 100 meshes.  

Thinking maybe we should consider using DA instead of Array in the main code base... maybe worth trying a branch out with some speed tests sometime.

**Comment by azrafe7** [comment]
Sure.... as long as we're talking about the openfl side of html, I'd be
glad to look into it. Great work so far, really!

About perf issues and DA:
the code is MIT, everyone can modify/optimize it, and I sincerely don't
have time to spend looking for possible speed gains by adding
 *dependencies* (not now by the way, as long as I'd like to publish a
_complete_ thing!).

I think it could be a thing worth considering only if some people using it
would complain for excessive slowness.

2015-02-10 2:07 GMT+01:00 Justinfront <notifications@github.com>:
