### ISSUE TITLE
packman

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#36]
Thinking the maze would be ideal for a packman style game and maybe could be implemented with not much effort?  Demos are to inspire and instruct so I am unsure if packman would be too complex. Or maybe we could create a game along these lines and release on mobile as opensource on git but pay on various stores? What are your thoughts.

http://gameinternals.com/post/2072558330/understanding-pac-man-ghost-behavior

On the openfl examples I noticed that for html5 
    <window width="0" height="0" if="html5" />
helps.

**Comment by azrafe7** [comment]
Ha, I remember reading the pacman dossier and actually thought about using
that info to make a pacman with touch controls and hxDaedalus.

Must admit that thinking more about it made me realize that it's not so
easy to decide how the path following should work (shortest path not always
being what a user might want), and, moreover, that the result would
probably not be a fun game to play with this type of interaction (may be
wrong, but that's where I got then ;).

Don't know, maybe a simpler "find the maze solution in x steps max", or
"color/explore the most of the maze"? Still trying to come up with
something fun&simple, but not there yet!

About js and openfl: best thing is to wait till things settle a bit, but
report issues as soon as we find them so they get included in 3.2
(snow/luxe and flambe suffer from the same problems).


2015-03-16 10:36 GMT+01:00 Justinfront <notifications@github.com>:
