### ISSUE TITLE
javax

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#37]
Javax is no longer valid package on java examples ( when trying RC )  I must update the haxelib, just waiting for a response on my query maybe only update when RC goes release.  Openfl html5 examples currently fail on RC ( well minor issues on html5 ) but probably resolved when new openfl, flash and canvas ones work fine.

**Comment by azrafe7** [comment]
With latest haxe 3.2 nightly (b6aa2c2):

 - pure js seems fine
 - thanks to @waneck's fix now java works with minor changes (`java.javax` and `@:overload override`)
 - I'm having problems with openfl html5 and cpp (weirdly nme is ok). Tried with git version but still no luck. Waiting for their next release...

When all is good we should probably document which versions of what are _safe_ to use.

**Comment by azrafe7** [comment]
Unrelated to this: 

I've been experimenting on how to improve performance of drawing entity/path in the openfl examples. It works really good when stamping the graphics onto a bitmap in real time (even for your multilayer demo), but it somewhat _complicates_ the code, so not sure we want to add it. What you think?

**Comment by Justinfront** [comment]
Which email should I use to talk off air?

**Comment by azrafe7** [comment]
azrafe7 at gmail dot com

Il venerdì 20 marzo 2015, Justinfront <notifications@github.com> ha scritto:
> Which email should I use to talk off air?
>
> —
> Reply to this email directly or view it on GitHub.<
https://ci5.googleusercontent.com/proxy/Da1QAtPZ4mspPhxXJQ9YYmN9hHsHC52brEy3_YXpKRh0xsqIWUkweYTkp6yKacaua9HNqszDwqS7hjsB7phH_Ue70cCI6aZVuGBQzbNruwSg3_WNtf0q5p2GSts7J2HkNXyZiXFfycP9PJKLyvQX7zOepEvANg=s0-d-e1-ft#https://github.com/notifications/beacon/ABNTD3BPKQC-R4h-U5Ta3eRVZAv8S8LUks5n23AogaJpZM4DvM5S.gif
>

**Comment by azrafe7** [comment]
btw haven't received any mail from you yet, not sure it's intentional.

**Comment by Justinfront** [comment]
Sorry it bounced was too big, so I left it.

**Comment by Justinfront** [comment]
Did you get anywhere with RC2 and openfl?  Probably best to keep openfl examples separate if they are not working fully with RC2... or are they for you?

**Comment by azrafe7** [comment]
Nope. They're still broken with openfl 3.0.0-beta (though they work if you pass `-Dv2` to the compiler). Let's wait for their next release.

**Comment by azrafe7** [comment]
Was looking into how to speed up the java examples and found some interesting bits of info involving BufferStrategy:

 - http://stackoverflow.com/questions/148478/java-2d-drawing-optimal-performance
 - http://stackoverflow.com/questions/7543136/efficient-methods-of-rapidly-redrawing-a-map-java-jpanel
 - http://www.gamedev.net/page/resources/_/technical/general-programming/java-games-active-rendering-r2418

Tested the example in the last link and it gave impressive performance (600+ FPS).

We might consider using that for SimpleView, but would require quite some changes. Would you be interested in implementing it?

**Comment by Justinfront** [comment]
Currently staying with my Brother's family in Cornwall so unlikely to 
touch computer much till after easter weekend but perhaps mixing slick2d 
would also help. Best Justin
