### ISSUE TITLE
MeshExtractionFromBitmap

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#41]
Happy Easter.
Noticed Daedalus had a new Demo "MeshExtractionFromBitmap".  I have added functionality to Daedalus and added a luxe demo to debug it.  Was not really intending to do much code down at my brothers but it looked an easy addition and I thought I should try making a luxe demo. Should have done a pull request but it does not impact other code and would have required one for each repository so A bit of a pain. I guess we should try to work out what other updates need moving from Daedalus to hxDaedalus. I am not too sure how to setup so you can view the result ( can you modify the readme on luxe? ), but result is pretty similar to the Daedalus one.  I suppose after easter I need to really think about 06.
Hope your having a good easter best Justin.

**Comment by azrafe7** [comment]
A retroactive happy Easter to you too! ;D

I see Cedric has done some minor changes to the lib, all of which seem pretty easy to port over.
Nice to see the new demo (also: luxe is starting to draw my attention). I've added a link to a compiled online version (if you want to do it yourself the next time, here's what is needed: build the example, switch to gh-pages branch, merge the master branch into the gh-pages one, commit the relevant files - might need some modifications to gitignore).
