### ISSUE TITLE
Luxe Pixel broken with haxe 3.2 and current Luxe/snow

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#42]
I tried to fix the problems with running the https://github.com/hxDaedalus/hxDaedalus-luxe-examples/blob/master/hxDaedalus-Luxe-Examples/07-MeshExtractionFromBitmap/src/Main.hx

But got stuck, the changes compile but then with the Tools.extractMeshFromBitmap in it crashes.

It seemed to complain about changes to Luxe texture in the hxDaedalus Pixel class the assets is now a promise, I tried changing the commented code below ( in two methods ) with the new code.

```
    //var data:snow.io.typedarray.Uint8Array = texture.asset.image.data;
    var get = Luxe.snow.assets.image( texture.id );
    var data: snow.api.buffers.Uint8Array;
    get.then(function(_asset:snow.types.Types.AssetImage) {
        data = _asset.image.pixels;
    });
```

but got stuck on the method applyToLuxeTexture in the pixel class.
//texture.reset();  // rebind texture
//texture.submit( data );  //<- should it be this now???

I rearranged the Luxe example as below due to a change in the way you access texture and loading, the texture does render on screen just dies after the pixel extraction?

package;

import hxDaedalus.data.math.Tools;
import hxDaedalus.graphics.TargetCanvas;
import hxDaedalus.graphics.SimpleDrawingContext;
import hxDaedalus.data.math.Point2D;
import luxe.Input.Key;
import luxe.Input.KeyEvent;
import luxe.Sprite;
import luxe.Vector;
import phoenix.Texture;

class Main extends luxe.Game {

```
// entry point
override function ready() {

    // white background
    Luxe.renderer.clear_color.rgb(0xFFFFFF);

    // get the asset
    var texture = Luxe.resources.texture('assets/MeshExtractionFromBitmap.png');

    // show the image
    var sprite = new Sprite({
        texture: texture,
        centered: false,
        pos: new Vector(110, 220),
        size: new Vector( texture.width, texture.height ),
        depth: -1
    });

    var vertices = new Array<Point2D>();
    var triangles = new Array<Int>();
    Tools.extractMeshFromBitmap( texture, vertices, triangles);

    // create a viewport
    var g = new SimpleDrawingContext( new TargetCanvas() );
    var dx = 310;
    var dy = 220;
    g.lineStyle(1, 0xFF0000);
    // use a 3 iterator instead?
    var i: Int = 0;
    while( i < triangles.length ){
        g.moveTo(vertices[triangles[i]].x + dx, vertices[triangles[i]].y + dy);
        g.lineTo(vertices[triangles[i+1]].x + dx, vertices[triangles[i+1]].y + dy);
        g.lineTo(vertices[triangles[i+2]].x + dx, vertices[triangles[i+2]].y + dy);
        g.lineTo(vertices[triangles[i]].x + dx, vertices[triangles[i]].y + dy);
        i+=3;
    }


}

override function onkeyup(e:KeyEvent) {

    if (e.keycode == Key.escape) {
        Luxe.shutdown();
    }

} // onkeyup

    // standard setup type stuff
override function config( config: luxe.AppConfig ) {

    config.preload.textures = [
        { id:'assets/MeshExtractionFromBitmap.png' }
    ];
    config.render.antialiasing = 4;
    return config;
}
```

} // Main

**Comment by azrafe7** [comment]
I've update [hxPixels](https://github.com/azrafe7/hxPixels/blob/master/src/hxPixels/Pixels.hx) a few days ago supportng latest Luxe, but haven't yet copied it over into hxDaedalus. Can you try and do that to see if it works (I have a problem with `texture.fetch()` on my machine, so I'm curious to know if it works on yours).

**Comment by Justinfront** [comment]
I asked about a few issues today then found the luxe repository updated so got latest git's and ndll, for some reason the haxelib git luxe seemed to take for ever was very painful to wait, but the test works on web but not yet on windows I have filed an issue.
https://github.com/underscorediscovery/snow/issues/75

I would like to add a curveTo type command with our other drawing commands, I have an implementaion in mind, so that I can render path data.  Thinking maybe we could move this aspect of the code into an 'hxMotifs' library and have hxPixel and hxMotifs as dependancies.  At work I am rendering svg's to canvas and using with hxDaedalus in some tests it works very well, but yet to find a good svg approach for opengl, I have seen there is a hx-nanovg but that still needs porting of nanosvg and is a c++ only implementation and quite complex, I have a rough svg to json parser in the form of a fast abstract I made probably not optimal and limited on cases, but then to create abstracts of string for nodes with switches inside would be messy and complex and it would probably only handle simple paths and cases, not very complete when you consider true complexity of svg scaling all over the place etc..like in https://github.com/millermedeiros/SVGParser
So this gave me the idea that general Motifs simple structure it uses is quite appealing even if a SVGParser to Motif compiler written in ocaml is probably needed for creating complex Motifs files from svg.  hxMotif seemed ideal then json could be fed it like luxe sprites or the drawing code standalone as in hxDaedalus, but used with any target or as a haxeremote.  As a while back when I abstracted the hxDaedalus core into another branch it seemed a better abstraction leaving more flexibility to others.

typedef Motifs = { commands: Array<abstractStringCommand> };
var motifsJson: Motifs = Json.parse( '{ "commands":[ "M 0.5 0.5","L 1.0, 1.0" ] }' );
motifsJson.renderTo( surface ); 

In luxe maybe you would use it more like a sprite

var motifsGraphic:MotifsGraphic = {
name: 'test1'
position: new Vector( 100, 100 );
location: new Vector( 50, 50 );
commands: [ "M 0.5 0.5","L 1.0, 1.0" ];
}

**Comment by Justinfront** [comment]
azrafe7 the problem was that obj file name and path length were too long!! I have raised an issue with hxcpp incase there is an easy way to get a warning in future, so code works fine :)  Maybe for your graphics problems check the __file__ in the windows.build for long file names and see if they are in the obj file as they maybe missing.

**Comment by azrafe7** [comment]
Then it's not the same issue I'm experiencing... at this point it's much likely that my case has to do with an old graphics card (though I really don't get why for it's working on web but not native).
Anyway now we're sure it works on your end, and that's good!

**Comment by azrafe7** [comment]
About hxMotif and hxPixels as separate libs: yeah, it could be a nice solution. I need to think about it more.

For a SVG parser (not sure it's what you need but) have you looked into thx.geom?
