### ISSUE TITLE
added curveTo

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#44]
Hi I added curveTo method because it's something I really need it may not be optimal yet, have implemented on all targets but may need more testing. sorry not to have created a branch will be using it directly. If you have ideas for improvements let me know, I am aware it's probably not ideal approach.

https://github.com/hxDaedalus/hxDaedalus/blob/master/src/hxDaedalus/graphics/luxe/SimpleDrawingContext.hx#L54

I have tried it with this test and it seems to work.

``` haxe
package;

import hxDaedalus.data.math.Tools;
import hxDaedalus.graphics.TargetCanvas;
import hxDaedalus.graphics.SimpleDrawingContext;
import hxDaedalus.data.math.Point2D;
import luxe.Input.Key;
import luxe.Input.KeyEvent;
import luxe.Sprite;
import luxe.Vector;
import phoenix.Texture;


class Main extends luxe.Game {

    // entry point
    override function ready() {

        // white background
        Luxe.renderer.clear_color.rgb(0xFFFFFF);

        // get the asset
        var texture = Luxe.resources.texture('assets/MeshExtractionFromBitmap.png');

        // show the image
        var sprite = new Sprite({
            texture: texture,
            centered: false,
            pos: new Vector(110, 220),
            size: new Vector( texture.width, texture.height ),
            depth: -1
        });

        var vertices = new Array<Point2D>();
        var triangles = new Array<Int>();
        Tools.extractMeshFromBitmap( texture, vertices, triangles);

        // create a viewport
        var g = new SimpleDrawingContext( new TargetCanvas() );
        var dx = 310;
        var dy = 220;
        g.lineStyle(1, 0xFF0000);
        // use a 3 iterator instead?
        var i: Int = 0;
        while( i < triangles.length ){
            g.moveTo(vertices[triangles[i]].x + dx, vertices[triangles[i]].y + dy);
            g.curveTo( vertices[triangles[i+1]].x + dx, vertices[triangles[i+1]].y + dy,vertices[triangles[i+2]].x + dx, vertices[triangles[i+2]].y + dy);
            g.lineTo(vertices[triangles[i]].x + dx, vertices[triangles[i]].y + dy);
            i+=3;
        }


    }

    override function onkeyup(e:KeyEvent) {

        if (e.keycode == Key.escape) {
            Luxe.shutdown();
        }

    } // onkeyup

        // standard setup type stuff
    override function config( config: luxe.AppConfig ) {

        config.preload.textures = [
            { id:'assets/MeshExtractionFromBitmap.png' }
        ];
        config.render.antialiasing = 4;
        return config;
    }

} // Main
```

**Comment by azrafe7** [comment]
Nice addition!

It should be safe to replace the anonymous {x, y} struct with Point2D, right? (that way we could also reuse the distanceTo() method already implemented)

**Comment by Justinfront** [comment]
we need to test if we can go with anonymous {x: Float,y: Float} in more places and maybe put any point functionality in a help using class, need to try some speed tests.  It seems every library has there own Point2D implementation but if we all used anonymous structures with helper classes it would make for more flexible integration and less changing code between Point2D implementations.
DistanceTo can be swapped.  Note in the object to triangle code I hard coded the step... we need more thought on the quadTo code in SimpleDrawingContext as it maybe is too heavy and needs adjustment. 
I started creating a VirtualSimpleDrawContext more aligned to generating path data like in Letters but am still thinking about integration aspects.
But we do need to think about Batcher we can't really just send random geom to the default batcher and expect good render times, we need a custom one maybe sending the object's to the object to triangle code on every fill! ?  Maybe ISimpleDrawingContext needs to be setup so we can draw to a bitmap or texture for each target in a double buffer type setup?
