### ISSUE TITLE
New Release before Haxe Conference?

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#47]
I am leaving for Haxe conference thursday afternoon, it would be good to update Haxelib, I know the latest Object to triangle is flaky but it's beyond most casual use so I think we can just add a comment that this function is work in progress.  I am unsure which targets need more work but would be good to get all the examples sorted before haxe conference or go with what we have? Just think it's worth having a new haxelib for any users at conference that want to experiment and we need to make sure it all runs well on mac and pc atleast against latest.

**Comment by azrafe7** [comment]
Luxe and openfl/nme examples should already be up-to-date.
Flambe is not currently compatible with haxe 3.2.0, and a new version hasn't been released yet (but should be in the works).
Haven't looked at the others in a while (I'll do if I have time).

**Comment by Justinfront** [comment]
Luxe should be up to date and js works. I will try to double check them as well but  I think I need to add ones that are missing.
