### ISSUE TITLE
BitmapMesh was incorrect and the portrace was failing.

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#51]
BitmapMesh was incorrect and the portrace was failing, I think the comments between the else were not working correctly in Portrace and types were incorrect for BitmapMesh so have adjusted and now works - sorry I used the online submit so the diff files are rather noisy.

With some test code with SVG's -> Image on NME I am having very slow mesh generation BitmapMesh or BitmapObject, especially on mobile need to find away to speed up or to allow it to be done in Enterframe loop if required, the svg complexity is somewhat beyond my control maybe just too many triangles are generated.

**Comment by Justinfront** [comment]
ok seems that changing 
object = BitmapObject.buildFromBmpData( bmd, 15 );
to use 15 reduces overhead significantly the shape simple stuff is really useful.  It would be good to do the buildFromBitmap with specification of pixels color ranges rather than specify white save on threshold call perhaps.

**Comment by azrafe7** [comment]
Mmmhh... I'd be glad to improve the performance of my _poor_ implementation of the algorithms in hxGeomAlgo. It supports potrace-like algos wih custom thresholding behaviour (see CCLabeler, IsoContours and MarchingSquares), and polyline-simplifyiers (RamerDouglasPeucker, VisvalingamWhyatt), among other things.

The lib is still a bit rough for my tastes (that's the main reason it's not on haxelib, yet). But if you can experiment with it and provide feedback I'd really appreciate it.
