### ISSUE TITLE
Added SVG drawing support.

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#53]
using an svg flag
-D svg
drawing will be done via svg this is better for smooth scaling but probably heavier ( also updated js examples ).
if you see any serious problems with code let me know and I can revert but this was something I probably needed sorry for my lazyness not to put in a pull request.

**Comment by azrafe7** [comment]
Nice!

A few minor things I found testing the js examples (which I hadn't done in a long time):

 - mouse click position is off when the window is scrolled down
 - in BitmapPathfinding the geom appears only after the first click
 - in PathFinding the scale of the svg is changed twice
 - some #flash define that could be safely removed

As I said just minor, easily fixable things.

**Comment by nanjizal** [comment]
I can't remember if anything happened with this but going to close this as probably not much call for SVG use right now.
