### ISSUE TITLE
buildFromRecord

### ISSUE THREAD

**Issue by qpaolo** [hxDaedalus/hxDaedalus#71]
Mesh has buildFromRecord function

https://github.com/hxDaedalus/hxDaedalus/blob/master/src/hxDaedalus/data/Mesh.hx#L107

But where can I get the `record`?

**Comment by Justinfront** [comment]
Hi qpaolo

That does not seem to be used directly in any of our examples, it seems to takes constraints as a string, for instance from a file and just does a simple split on the content, it looks pretty useless unless your loading in constraints from a file. 

If you look at extracting a mesh from a bitmap in Tools it should give you an idea of it's use:
https://github.com/hxDaedalus/hxDaedalus/blob/master/src/hxDaedalus/data/math/Tools.hx#L55

There is an example use case of Tools in 
https://github.com/hxDaedalus/hxDaedalus-luxe-examples/blob/master/hxDaedalus-Luxe-Examples/07-MeshExtractionFromBitmap/src/Main.hx

Curious to see what your using library for.

Hope that helps?

Best

Justin

**Comment by qpaolo** [comment]
I want to save the meshes to the database and do the pathfinding when client make a REST request.  
So basically I want to be able to serialize the meshes and deserialize them.

**Comment by Justinfront** [comment]
rather than use this I would suggest you look at 
https://haxe.org/manual/std-serialization.html
there might even be better serialization er...  
https://github.com/ncannasse/hxbit
