### ISSUE TITLE
add me back :)

### ISSUE THREAD

**Issue by Justinfront** [hxDaedalus/hxDaedalus#73]
Azrafe7, can you add Nanjizal as owners, want to move forward with all my new code on Nanjizal as my work situation is no longer restrictive, so prefer to contribute via nanjizal in future.
Would like to branch wings to a separate repository and see if I can get a prototype working with Kha.

**Comment by azrafe7** [comment]
I'm on mobile currently and it doesn't make me add you to the team for
some reason. But I managed to add you as collaborator with admin role
(you should have received an invite).

Sorry, will fix it as soon as I'm on the pc.

2017-06-20 11:24 GMT+02:00, Justinfront <notifications@github.com>:

**Comment by azrafe7** [comment]
On PC finally... you should have received some invites as team member/owner.
