### ISSUE TITLE
Infinite loop in Mesh

### ISSUE THREAD

**Issue by BambooBandit** [hxDaedalus/hxDaedalus#79]
Hello, I recently made this issue for the java version of this library over at https://github.com/implicit-invocation/jwalkable/issues/10

Basically, my scene is very complex and after adding enough polygons to the mesh, the next polygon I add will freeze it in an infinite loop. So I did some digging around in the code, and found EPSILON and EPSILON_SQUARED in https://github.com/hxDaedalus/hxDaedalus/blob/master/src/hxDaedalus/data/Constants.hx

and I noticed some commented-out values in the original library. It made me think to try them. No luck. But I tried making them even smaller, EPSILON being 0.00001 and my infinite loop went away. My question is, what do these values do? Does my change need considerations that you know of? Thanks!

**Comment by nanjizal** [comment]
Epsilon is used mainly for checking bounds. So the squared version is just for when using Pythag ( checking 2D vector distance )  when avoiding calculating all the square roots.
The value of Epsilon really depends on the dimensions your using, for instance allows the rectangles added to be slightly bigger to account for detection being within epsilon.

Originally abstract enums where used as they maybe faster as Haxe will definitely replace the values in the code, it looks like it has been changed to allow them to be used directly in JS. Abstracts in haxe are great to reduce runtime performance but they disappear on targets so are not so ideal if used as a library on a target, so commented out code is purely a change  to add js exposure to be simpler.

In Geom2d Epsilon is used in the hit test ( ie deciding if something is corner, side or edge ), so smaller value will for instance make it harder for a detection of a corner point, I think so it can therefore influence the granularity of the triangulation... ie it's not always ideal to make the values too small.  Really small values will sometimes result in division by 0 errors. 

But yes try tweak it when you get infinite loops, as there is a balance between too many triangles and enough, and similar with path finding etc...  ( or scale up your dimensions and just down scale your drawing ). If you setup your code to see the triangulation I suspect sometimes you will find in your tests that either reducing epsilon will take longer and/or create more triangles, but feel free to do some experiments and paste findings.

You should in theory adjust EPSILON to always be the square root of EPSILON_SQUARED, but there is no reason you can't adjust them as as a pair as required but may not be ideal to change them permanantly in the library, there is a balance between code compution and accuracy.

Maybe best to just to draw to larger scale, but render to smaller scale, as that will help avoid gettting into very small values but provide the accuracy you need.

There maybe some tricks that could be added to detect the issue you found but currently the user base is small so does not seem to warrent reworks and improving, although at some stage I may add native webgl demo.

Best Justin (justinfront/nanjizal).

**Comment by BambooBandit** [comment]
Thanks for the info! I tried upscaling everything rather than making epsilon smaller. I don't notice a difference in speed in either solution, but upscaling did also fix the infinite loop, so I'm going to stick with that approach.
